# Generated by Django 4.1.1 on 2022-11-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0010_remove_alumno_legajo_alter_alumno_dictado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago_alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cursos.alumno')),
            ],
        ),
    ]
