# Generated by Django 4.1.1 on 2023-10-22 00:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Solo se permiten letras y espacios.', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_text', message='<i class="fa-solid fa-xmark"></i> Debe contener letras y/o espacios.', regex='^[A-Za-záéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('area', models.PositiveSmallIntegerField(choices=[(0, 'Capacitación'), (1, 'Cultura'), (2, 'Gimnasio')])),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.rol')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('cupo', models.PositiveIntegerField(help_text='capacidad maxima del aula')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, help_text='costo total del curso', max_digits=10)),
                ('nombre', models.CharField(max_length=50)),
                ('modulos', models.PositiveIntegerField(help_text='cantidad de horas del curso')),
                ('requiere_certificado', models.BooleanField()),
                ('periodo_pago', models.PositiveSmallIntegerField(choices=[(1, 'mes'), (2, 'clase')])),
                ('descuento', models.PositiveIntegerField(help_text='porcentaje de descuento')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Dictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, help_text='costo', max_digits=10)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictado', to='cursos.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.rol')),
                ('capacitaciones', models.CharField(max_length=50)),
                ('ejerce_desde', models.DateField()),
                ('actividades', models.ManyToManyField(blank=True, to='cursos.actividad')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.dictado')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='profesor',
            name='dictados',
            field=models.ManyToManyField(blank=True, related_name='profesores', through='cursos.Titular', to='cursos.dictado'),
        ),
        migrations.CreateModel(
            name='Pago_profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago_profesor', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto pagado', max_digits=10)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cursos.titular')),
            ],
        ),
        migrations.CreateModel(
            name='Pago_alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago_alumno', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto pagado', max_digits=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='cursos.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dictado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clase', to='cursos.dictado')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia_profesor', models.DateTimeField(auto_now_add=True)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia_profesor', to='cursos.titular')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia_alumno', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='cursos.alumno')),
                ('dictado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.dictado')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='dictado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='cursos.dictado'),
        ),
    ]
