# Generated by Django 4.1.1 on 2024-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictado',
            name='legajo',
            field=models.CharField(default='8554', max_length=4, null=True),
        ),
    ]
