# Generated by Django 4.1.1 on 2024-04-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictado',
            name='legajo',
            field=models.CharField(default='6022', max_length=4, null=True),
        ),
    ]
