# Generated by Django 4.1.1 on 2024-04-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_dictado_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictado',
            name='legajo',
            field=models.CharField(default='7830', max_length=4, null=True),
        ),
    ]
