# Generated by Django 4.1.1 on 2024-04-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_dictado_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictado',
            name='legajo',
            field=models.CharField(default='6370', max_length=4, null=True),
        ),
    ]
