# Generated by Django 4.1.1 on 2024-05-13 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_dictado_legajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictado',
            name='cupo_real',
            field=models.PositiveIntegerField(help_text='Máximo inscriptos', validators=[django.core.validators.MinValueValidator(1, message='Valor mínimo permitido es 1.'), django.core.validators.MaxValueValidator(100, message='Valor máximo es 100.')]),
        ),
        migrations.AlterField(
            model_name='dictado',
            name='legajo',
            field=models.CharField(default='1997', max_length=4, null=True),
        ),
    ]
