# Generated by Django 4.1.1 on 2024-05-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_remove_profesor_dictados_alter_dictado_cupo_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='dictados',
            field=models.ManyToManyField(blank=True, related_name='profesores', through='cursos.Titular', to='cursos.dictado'),
        ),
        migrations.AlterField(
            model_name='dictado',
            name='legajo',
            field=models.CharField(default='3540', max_length=4, null=True),
        ),
    ]
