# Generated by Django 4.1.1 on 2024-04-04 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0001_initial'),
        ('personas', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_alquiler', models.DateTimeField(blank=True, null=True)),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Noche', 'Noche')], max_length=50)),
                ('seguro', models.DecimalField(decimal_places=2, help_text='costo del alquiler', max_digits=10)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='afiliados.afiliado')),
                ('lista_espera', models.ManyToManyField(blank=True, to='afiliados.afiliado')),
            ],
            options={
                'permissions': [('permission_gestion_alquiler', 'Control total alquiler')],
            },
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.rol')),
                ('dictados', models.ManyToManyField(blank=True, related_name='encargados', to='cursos.dictado')),
            ],
            bases=('personas.rol',),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('localidad', models.CharField(choices=[('RAWSON', 'Rawson'), ('PUERTO MADRYN', 'Puerto Madryn'), ('GAIMAN', 'Gaiman'), ('TRELEW', 'Trelew')], max_length=25)),
                ('direccion', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField(help_text='capacidad maxima del salon')),
                ('precio', models.DecimalField(decimal_places=2, help_text='costo del alquiler', max_digits=10)),
                ('fecha_baja', models.DateTimeField(auto_now_add=True, null=True)),
                ('tipo_salon', models.PositiveSmallIntegerField(choices=[(1, 'Polideportivo'), (2, 'Multiuso')])),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon', to='alquileres.encargado')),
                ('servicios', models.ManyToManyField(blank=True, to='alquileres.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Pago_alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, null=True)),
                ('forma_pago', models.CharField(choices=[('total', 'Total'), ('cuota', 'Cuota')], max_length=30)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='alquileres.alquiler')),
            ],
        ),
        migrations.AddField(
            model_name='alquiler',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='alquileres.salon'),
        ),
    ]
