# Generated by Django 4.1.1 on 2024-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='fecha_baja',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='cambio_inquilino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Confirmado'), (2, 'En curso'), (3, 'Finalizado'), (4, 'Cancelado')], default=1),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fechaBaja',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='fechaBaja',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='capacidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salon',
            name='localidad',
            field=models.CharField(choices=[('', '--------'), ('RAWSON', 'Rawson'), ('PUERTO MADRYN', 'Puerto Madryn'), ('GAIMAN', 'Gaiman'), ('TRELEW', 'Trelew')], max_length=25),
        ),
    ]
