# Generated by Django 4.1.1 on 2022-11-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_profesor_actividades_alter_profesor_dictados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='actividades',
            field=models.ManyToManyField(blank=True, to='cursos.actividad'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='dictados',
            field=models.ManyToManyField(blank=True, related_name='profesores', through='cursos.Titular', to='cursos.dictado'),
        ),
    ]
