# Generated by Django 4.1.1 on 2022-11-13 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_profesor_actividades_alter_profesor_dictados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='dictado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.dictado'),
        ),
    ]
