# Generated by Django 4.1.1 on 2022-11-13 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_curso_dictado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Costo',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
