# Generated by Django 4.1.1 on 2022-11-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_rename_costo_curso_costo_rename_nombre_curso_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='dictado',
        ),
        migrations.AddField(
            model_name='dictado',
            name='curso',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='cursos.curso'),
            preserve_default=False,
        ),
    ]
