# Generated by Django 4.1.1 on 2022-11-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_remove_curso_dictado_dictado_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='clase',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
