# Generated by Django 4.1.1 on 2022-11-25 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_clase_hora_fin_alter_clase_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='legajo',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dictado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='cursos.dictado'),
        ),
    ]
