# Generated by Django 4.1.1 on 2022-11-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.rol')),
                ('razon_social', models.CharField(max_length=50)),
                ('cuit_empleador', models.CharField(max_length=8)),
                ('categoria_laboral', models.CharField(max_length=20)),
                ('domicilio_empresa', models.CharField(max_length=50)),
                ('localidad_empresa', models.CharField(max_length=50)),
                ('rama', models.CharField(max_length=50)),
                ('fechaIngresoTrabajo', models.DateField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('horaJornada', models.PositiveIntegerField()),
                ('fechaAfiliacion', models.DateField(auto_now=True)),
                ('estado', models.BooleanField(default=False)),
            ],
            bases=('personas.rol',),
        ),
    ]
