# Generated by Django 4.1.1 on 2022-10-11 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0005_alter_persona_celular_alter_persona_cuil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.rol')),
                ('razon_social', models.CharField(max_length=50)),
                ('cuit_empleador', models.CharField(max_length=8)),
                ('categoria_laboral', models.CharField(max_length=20)),
                ('domicilio_empresa', models.CharField(max_length=50)),
                ('localidad_empresa', models.CharField(max_length=50)),
                ('rama', models.CharField(max_length=50)),
            ],
            bases=('personas.rol',),
        ),
    ]
