# Generated by Django 4.1.1 on 2022-10-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='fechaAfiliacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='fechaIngresoTrabajo',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afiliado',
            name='fechaNacimiento',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afiliado',
            name='horaJornada',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afiliado',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
