# Generated by Django 4.1.1 on 2022-11-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='fechaAfiliacion',
            field=models.DateField(),
        ),
    ]
