# Generated by Django 4.1.1 on 2022-11-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0002_alter_afiliado_fechaafiliacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='cuit_empleador',
            field=models.CharField(max_length=10),
        ),
    ]
