# Generated by Django 4.1.1 on 2022-10-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('estado_civil', models.PositiveSmallIntegerField(choices=[(1, 'soltero'), (2, 'casado'), (3, 'viudo')])),
                ('cuil', models.CharField(max_length=8)),
                ('celular', models.CharField(max_length=30)),
                ('encargado', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'afiliado'), (2, 'profesor'), (3, 'alumno')])),
                ('desde', models.DateTimeField(auto_now_add=True)),
                ('hasta', models.DateTimeField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='personas.persona')),
            ],
        ),
    ]
