# Generated by Django 4.1.1 on 2022-11-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('estado_civil', models.PositiveSmallIntegerField(choices=[(1, 'soltero'), (2, 'casado'), (3, 'viudo')])),
                ('cuil', models.CharField(max_length=8)),
                ('celular', models.CharField(max_length=30)),
                ('es_afiliado', models.BooleanField(default=False)),
                ('es_alumno', models.BooleanField(default=False)),
                ('es_profesor', models.BooleanField(default=False)),
                ('es_encargado', models.BooleanField(default=False)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'afiliado'), (0, 'alumno'), (2, 'profesor')])),
                ('desde', models.DateTimeField(auto_now_add=True)),
                ('hasta', models.DateTimeField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'hijo'), (2, 'conyuge'), (3, 'padre'), (4, 'madre'), (5, 'hermano'), (6, 'tutor')])),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to='personas.persona')),
            ],
        ),
    ]
