# Generated by Django 4.1.1 on 2022-09-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='celular',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='cuil',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.PositiveSmallIntegerField(choices=[(1, 'soltero'), (2, 'casado'), (3, 'viudo')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='mail',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(default='Argentino', max_length=50),
            preserve_default=False,
        ),
    ]
