# Generated by Django 4.1.1 on 2022-11-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.CharField(max_length=12),
        ),
    ]
