# Generated by Django 4.1.1 on 2022-10-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='encargado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'afiliado'), (0, 'alumno')]),
        ),
    ]
