# Generated by Django 4.1.1 on 2022-11-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='personas.persona'),
        ),
    ]
