# Generated by Django 4.1.1 on 2022-10-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_encargado_alter_persona_celular_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='encargado',
            field=models.BooleanField(default=False),
        ),
    ]
