# Generated by Django 4.1.1 on 2022-11-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_familiar_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVinculo', models.PositiveSmallIntegerField(choices=[(0, 'Conyuge'), (1, 'Hijo'), (2, 'Tutor')])),
                ('vinculado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculantes', to='personas.persona')),
                ('vinculante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculados', to='personas.persona')),
            ],
        ),
        migrations.DeleteModel(
            name='Familiar',
        ),
        migrations.AddField(
            model_name='persona',
            name='familia',
            field=models.ManyToManyField(through='personas.Vinculo', to='personas.persona'),
        ),
    ]
