# Generated by Django 4.1.1 on 2022-11-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_vinculo_delete_familiar_persona_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='persona',
            name='familia',
            field=models.ManyToManyField(blank=True, null=True, through='personas.Vinculo', to='personas.persona'),
        ),
    ]
