# Generated by Django 4.1.1 on 2022-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_persona_cuil_alter_persona_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'afiliado'), (3, 'alumno'), (2, 'profesor')]),
        ),
    ]
