# Generated by Django 4.1.1 on 2022-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_rol_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='familia',
            field=models.ManyToManyField(blank=True, through='personas.Vinculo', to='personas.persona'),
        ),
    ]
