# Generated by Django 4.1.1 on 2024-05-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afiliado',
            options={},
        ),
    ]
