# Generated by Django 4.1.1 on 2024-04-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0002_alter_afiliado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afiliado',
            options={'permissions': [('permission_gestion_afiliado', 'Control total afiliado')]},
        ),
    ]
