# Generated by Django 4.1.1 on 2023-09-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0002_mimodelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiModelo',
        ),
    ]
