# Generated by Django 4.1.1 on 2024-04-08 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0003_alter_afiliado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='categoria_laboral',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='Solo se permiten letras, números y espacios, con o sin tildes.', regex='^[A-Za-z0-9\\sñÑáéíóúÁÉÍÓÚ]+$')]),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='domicilio_empresa',
            field=models.CharField(help_text='Calle y numero', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_text', message='Solo se permiten letras, números y espacios, con o sin tildes.', regex='^[A-Za-z0-9\\sñÑáéíóúÁÉÍÓÚ]+$')]),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='localidad_empresa',
            field=models.CharField(choices=[('', '--------'), ('RAWSON', 'Rawson'), ('PUERTO MADRYN', 'Puerto Madryn'), ('GAIMAN', 'Gaiman'), ('TRELEW', 'Trelew')], default='TRELEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='razon_social',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_text', message='Solo se permiten letras, números y espacios, con o sin tildes.', regex='^[A-Za-z0-9\\sñÑáéíóúÁÉÍÓÚ]+$')]),
        ),
    ]
